# Execute SuricataLog scripts from the Docker image
# docker compose up --detach
# docker compose exec suricatalog eve_log /suricatalog/eve.json
---
services:
  suricatalog:
    container_name: suricatalog
    image: suricatalog:latest
    volumes:
      - type: bind
        source: /var/log/suricata
        target: /suricatalog
        read_only: true
    restart: always
    tty: true
    build:
        context: "."
        dockerfile: Dockerfile
        network: host