# Run code through Ruff, Yamllint, Shellcheck
---
name: Suricata log code linting
permissions:
  contents: read
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.11'
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v3
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --editable .[dev,lint]
      - name: Check packaging with twine
        run: |
          python -m build .
          twine check dist/suricatalog-*.whl
      - name: Analysing the SuricataLog code with Ruff
        run: |
          ruff check suricatalog
          ruff check test
      - name: Analysing the SuricataLog code with Yamllint
        run: |          
          yamllint etc/suricata/suricata.yaml docker-compose.yml
      - name: Analysing the SuricataLog code with Shellcheck
        run: |          
          shellcheck scripts/replay_pcap_file.sh